#!/bin/bash

. ${TOOL_DIR}/functions

function brief()
{
    echo "--test-tinyxml2=[no|<path>]"
}

function help()
{
    brief
    cat <<EOF
    If this option is given with a <path> to the tinyxml2 source tree, the full tree will be imported
    on the target under /data/tinyxml2 from which you can execute the tinyxml2 test suite using:

    cd /data/tinyxml2/qnx/test
    ./qnxtest.sh

    NOTE: You must compile the tinyxml2 source tree of the desired target before building
    the vm image.

    The default is no.
EOF
}

function validate() {

	if [ ${OPT_TEST_TINYXML2} != "no" ]; then
		if [ ! -d "${OPT_TEST_TINYXML2}" ]; then
			echo "Invalid tinyxml2 source tree '${OPT_TEST_TINYXML2}'"
			exit 1;
		fi
	else
		exit 0;
	fi
}

function configure()
{
	rm -f output/option_files/*.opt_test_tinyxml2
	if [ "$OPT_TEST_TINYXML2" != no ]; then
		if [ "${OPT_VERBOSE}" == "yes" ]; then
			echo "Building tinyxml2 file list from ${OPT_TEST_TINYXML2}"
		fi

		for f in $(find ${OPT_TEST_TINYXML2} -type f); do
			echo "[perms=0755] tinyxml2/${f#${OPT_TEST_TINYXML2}/}=${f}" >> output/option_files/data_files.opt_test_tinyxml2
		done;

		case ${OPT_ARCH} in
		x86*)
			TINYXML2_TEST_PREFIX="nto-${OPT_ARCH}-o";
			;;
		*aarch64*)
			TINYXML2_TEST_PREFIX="nto-aarch64-le";
			;;
		esac

		# export tinyxml2 options"
		echo "TINYXML2_TEST_PREFIX=${TINYXML2_TEST_PREFIX}" >> output/option_files/ifs_env.opt_test_tinyxml2

	fi

	exit 0
}

case "$1" in
	brief)
		brief;;
	help)
		help;;
	validate)
		validate;;
	configure)
		configure;;
	default)
		echo no;;
esac
